spring.application.name=placementprep

# Local Database Settings (Will be overridden in prod by NEON DB URL)
spring.datasource.url=${DB_URL:jdbc:h2:mem:placementprep}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driverClassName=${DB_DRIVER:org.h2.Driver}

spring.jpa.properties.hibernate.dialect=${DB_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Settings
jwt.secret=${JWT_SECRET:9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9}
jwt.expirationMs=86400000

# Cloudinary
cloudinary.url=${CLOUDINARY_URL:cloudinary://534524856291424:f9qvyvHqRwNoH5t08v9ctDv-W0Q@datakkowq}

# Remotive URL
remotive.api.url=https://remotive.com/api/remote-jobs

# Gemini API
gemini.api.key=${GEMINI_API_KEY:AIzaSyChih7HzI0-Ulgf_8rFT9FeBakTFnsgCZk}

# Judge0 API
judge0.api.key=${JUDGE0_API_KEY:mock_key}
judge0.api.host=${JUDGE0_API_HOST:mock_host}
